### ISSUE TITLE
Imgur no longer allows API V2

### ISSUE THREAD

**Issue by asalgat** [Salgat/RedditBoost#100]
This is pretty bad since it means you need an account to use the API (v3) I believe. I'm going to make sure if I can update this to the new API, but it might be a non-fixable issue.

**Comment by eramdam** [comment]
Hi, 
I use RedditBoost (awesome work!) but I also develop [Better TweetDeck](https://github.com/eramdam/BetterTweetDeck) and it uses the Imgur API v3. The only individual needing an account is me, the developer to get some Imgur API keys. I guess it should not be too hard for you to update your code in that case :) (Feel free to watch [BTD's](https://github.com/eramdam/BetterTweetDeck/blob/master/source/js/Providers.js) implementation if you want)

**Comment by Salgat** [comment]
Hey @eramdam, after looking at your source and checking out the docs, I think you're right. I'll try to get to it sometime this weekend, I appreciate your help!

**Comment by eramdam** [comment]
@Salgat Well, I know my users never had to create an Imgur account so I guess in your case it should be pretty easy.

Btw: I wanted to contribute to the project but the given Typescript command fails with
`error TS6082: Only 'amd' and 'system' modules are supported alongside --out.`

I never did any Typescript (for now!) so I don't know how safe it is to modify `tsconfig.json` so maybe you would want to update your README :)

**Comment by Salgat** [comment]
Hmm, seems to be related to the newest version of TypeScript, I'll check out what's going on.

**Comment by Salgat** [comment]
@eramdam Alright sorry for that, fixed and tested the issue; the develop branch now has the fixed tsconfig.json.
