### ISSUE TITLE
Add mirror functionality

### ISSUE THREAD

**Issue by asalgat** [Salgat/RedditBoost#44]
This is a long shot, but look into if any reddit mirror sites exist, or even using google cache if possible?

**Comment by Salgat** [comment]
http://www.page2images.com/convert_url_to_image_api_rate_plans

This seems to be a free service for hosting mirrors. Another option is https://np.reddit.com/r/Website_Mirror_Bot/wiki/faq which uses imgur and cutycapt to produce and store the website screenshots. Another option is to use http://archive.is/

**Comment by Salgat** [comment]
Addressed by the latest release.
